language: c
sudo: required
dist: trusty
matrix:
  include:
    - compiler: clang
      env: c_tests=y PYTHON=pypy JAVA=java JAVAC=javac NPM=npm
    - compiler: gcc
      env: c_tests=y PYTHON=python3.5
    - compiler: gcc
      env: PYTHON=python3.3
    - compiler: gcc
      env: PYTHON=python2.7
    - compiler: gcc
      env: PYTHON=python2.6
# Try to check out a branch of the same name from the snowball-data repo
# sibling of this snowball repo, so that PRs requiring changes to both can be
# CI tested easily.
#
# If that fails, just clone the standard snowball-data repo with the same
# branch name, falling back to the default branch.
before_install:
  - git clone --depth=1 -b "$TRAVIS_BRANCH" https://github.com:"${TRAVIS_REPO_SLUG%%/*}"/snowball-data.git || git clone --depth=1 -b "$TRAVIS_BRANCH" https://github.com/snowballstem/snowball-data.git || git clone --depth=1 https://github.com/snowballstem/snowball-data.git
script:
  - test -z "$c_tests" || make
  - test -z "$c_tests" || make check STEMMING_DATA=snowball-data
  - test -z "$PYTHON" || make check_python python="$PYTHON" STEMMING_DATA=snowball-data
  - test -z "$JAVA" -o -z "$JAVAC" || make check_java STEMMING_DATA=snowball-data
  - test -z "$NPM" || "$NPM" install -g jsx
  - test -z "$NPM" || make check_jsx STEMMING_DATA=snowball-data
